# Generated by Django 3.2 on 2021-11-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Institute_State', models.CharField(max_length=70)),
                ('Institute_District', models.CharField(max_length=70)),
                ('Name_of_Collage', models.CharField(max_length=70)),
                ('Name_of_university', models.CharField(max_length=70)),
                ('Institute_Type', models.CharField(max_length=70)),
                ('Institute_City', models.CharField(max_length=70)),
                ('Institute_pincode', models.CharField(max_length=70)),
                ('Institute_Email_id', models.CharField(max_length=70)),
                ('Institute_Mobile_No', models.IntegerField()),
            ],
        ),
    ]
